# Before anything:
# In Visual studio code Go to : view => Terminal => And type this : pip install pytube
# Then do right click on youTube_downloader.py and choose Run python file in terminal
# Then paste link of the playlist you want "")
from pytube import YouTube
from pytube import Playlist

# Prompt the user to input the YouTube playlist URL
playlist_url = input("Enter the YouTube playlist URL: ")

# Create a Playlist object by passing the playlist URL
playlist = Playlist(playlist_url)

# Specify the output directory where the videos will be saved
output_directory = "D:\Courses\Template-HTML-CSS-JS"

# Iterate over each video in the playlist
for video_url in playlist.video_urls:
    try:
        # Create a YouTube object by passing the video URL
        youtube = YouTube(video_url)

        # Filter the video streams to select 720p resolution
        video_stream = youtube.streams.filter(res="720p").first()

        # Download the video
        video_stream.download(output_directory)

        print(f"Video downloaded successfully: {youtube.title}")
    except Exception as e:
        print(f"Error downloading video: {video_url}")
        print(str(e))

print("Playlist downloaded successfully!")

# Code generated by Chat-Gpt and maintained by me to use it for downloading playlists 
# not only for single videos